# Generated by Django 5.0 on 2023-12-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
